- name: Restart Containerd
  become: true
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: true

- name: Restart Kubelet
  become: true
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
    enabled: true