---
- name: Kubeadm create token
  register: token
  changed_when: true
  ansible.builtin.command: kubeadm token create --print-join-command

- name: "Add K8S Token and Hash to dummy host"
  add_host:
    name: "K8S"
    token: "{{ token.stdout }}"
