---
- name: Install Docker
  hosts: all
  tasks:
    - name: Add Docker Repo
      ansible.builtin.command:
        cmd: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo
    - name: Install docker
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: installed
    - name: Default containered config
      changed_when: true
      ansible.builtin.shell: |
        set -o pipefail
        containerd config default | sed 's/SystemdCgroup = false/SystemdCgroup = true/' | tee /etc/containerd/config.toml
    - name: Start docker
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
        enabled: true
      with_items:
        - docker
        - containerd
