---
- name: Install Kubernetes
  hosts: all
  tasks:
    - name: Modules config
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        mode: "0644"
        content: |
          overlay
          br_netfilter
    - name: Load overlay module
      community.general.modprobe:
        name: overlay
        state: present
    - name: Load netfilter module
      community.general.modprobe:
        name: br_netfilter
        state: present
    - name: Load sysctl configs
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: '1'
        sysctl_file: /etc/sysctl.d/k8s.conf
        reload: true
      with_items:
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-ip6tables
        - net.ipv4.ip_forward
    - name: Remove swap
      ansible.posix.mount:
        path: none
        fstype: swap
        state: absent
    - name: Disable swap
      ansible.builtin.command: swapoff -a
      register: swapout
      when: ansible_swaptotal_mb > 0
      changed_when: swapout.rc == 0
    - name: Kubernetes Repo
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/kubernetes.repo
        mode: "0644"
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
          enabled=1
          gpgcheck=1
          gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
          exclude=kubelet kubeadm kubectl
    - name: Install kubernetes
      ansible.builtin.dnf:
        name:
          - kubelet
          - kubeadm
          - kubectl
          - python3-pip
        state: installed
        disable_excludes: kubernetes
    - name: Install ansible requisites
      ansible.builtin.pip:
        name:
          - kubernetes
    - name: Start docker
      ansible.builtin.systemd:
        name: kubelet
        state: restarted
        enabled: true
